/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.testgui.view;

import java.awt.Color;

/**
 *
 * @author ASUS X
 */
public class inM extends javax.swing.JFrame {

    /**
     * Creates new form inM
     */
    public inM() {
        initComponents();
        AMname.setBackground(new Color(0,0,0,64));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        RippleMiniLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        leaderbordbtn = new javax.swing.JLabel();
        Faq = new javax.swing.JLabel();
        Donate = new javax.swing.JLabel();
        AboutMe = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Homepej = new javax.swing.JPanel();
        Homepage = new javax.swing.JLabel();
        HomepageBg = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Ripple = new javax.swing.JPanel();
        logocaduk = new javax.swing.JLabel();
        howdypanel = new javax.swing.JPanel();
        howdy = new javax.swing.JLabel();
        wlcmb = new javax.swing.JLabel();
        DonatePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FaqGames = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        leaderboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AboutmePanel = new javax.swing.JPanel();
        aboutmepng = new javax.swing.JPanel();
        aboutmetxt = new javax.swing.JLabel();
        pict = new javax.swing.JLabel();
        AMname = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 540));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(255, 255, 255));

        RippleMiniLogo.setIcon(new javax.swing.ImageIcon("D:\\text-black.png")); // NOI18N

        jLabel4.setText("Logout");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        leaderbordbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaderbordbtn.setText("Leaderboard");
        leaderbordbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaderbordbtnMouseClicked(evt);
            }
        });

        Faq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Faq.setText("Faq");
        Faq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FaqMouseClicked(evt);
            }
        });

        Donate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Donate.setText("Donate <3");
        Donate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonateMouseClicked(evt);
            }
        });

        AboutMe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutMe.setText("About me");
        AboutMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMeMouseClicked(evt);
            }
        });

        jTextField1.setText("Looking for someone ? ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RippleMiniLogo)
                .addGap(45, 45, 45)
                .addComponent(leaderbordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Faq, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Donate, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutMe, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Faq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RippleMiniLogo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(AboutMe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Donate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(leaderbordbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        Homepej.setBackground(new java.awt.Color(255, 255, 255));
        Homepej.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Homepage.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Homepage.setForeground(new java.awt.Color(255, 255, 255));
        Homepage.setText("Home Page");
        Homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomepageMouseClicked(evt);
            }
        });
        Homepej.add(Homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 70));

        HomepageBg.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS X\\Pictures\\orig_545271.jpg")); // NOI18N
        HomepageBg.setText("dsadsadas");
        Homepej.add(HomepageBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 80));

        mainPanel.add(Homepej, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 760, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.CardLayout());

        Ripple.setBackground(new java.awt.Color(255, 255, 255));

        logocaduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/testgui/view/ikon goblog'.png"))); // NOI18N

        howdypanel.setBackground(new java.awt.Color(255, 255, 255));
        howdypanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 222, 223)));

        howdy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        howdy.setText("Howdy! Om Rama ");

        wlcmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        wlcmb.setText("Welcome back to Ripple. We currently have 96 online users and 49008 total registed users. Nice day to farm a few maps, isn't it?");

        javax.swing.GroupLayout howdypanelLayout = new javax.swing.GroupLayout(howdypanel);
        howdypanel.setLayout(howdypanelLayout);
        howdypanelLayout.setHorizontalGroup(
            howdypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howdypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(howdy, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(wlcmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        howdypanelLayout.setVerticalGroup(
            howdypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(howdypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(howdy)
                .addGap(18, 18, 18)
                .addComponent(wlcmb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RippleLayout = new javax.swing.GroupLayout(Ripple);
        Ripple.setLayout(RippleLayout);
        RippleLayout.setHorizontalGroup(
            RippleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RippleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(howdypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RippleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logocaduk)
                .addGap(220, 220, 220))
        );
        RippleLayout.setVerticalGroup(
            RippleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RippleLayout.createSequentialGroup()
                .addComponent(logocaduk, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(howdypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel4.add(Ripple, "card2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/testgui/view/donate.PNG"))); // NOI18N

        javax.swing.GroupLayout DonatePanelLayout = new javax.swing.GroupLayout(DonatePanel);
        DonatePanel.setLayout(DonatePanelLayout);
        DonatePanelLayout.setHorizontalGroup(
            DonatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DonatePanelLayout.setVerticalGroup(
            DonatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonatePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(DonatePanel, "card5");

        FaqGames.setPreferredSize(new java.awt.Dimension(760, 400));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/testgui/view/osh.PNG"))); // NOI18N

        javax.swing.GroupLayout FaqGamesLayout = new javax.swing.GroupLayout(FaqGames);
        FaqGames.setLayout(FaqGamesLayout);
        FaqGamesLayout.setHorizontalGroup(
            FaqGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FaqGamesLayout.setVerticalGroup(
            FaqGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FaqGamesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(FaqGames, "card4");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/testgui/view/rank.png"))); // NOI18N

        javax.swing.GroupLayout leaderboardLayout = new javax.swing.GroupLayout(leaderboard);
        leaderboard.setLayout(leaderboardLayout);
        leaderboardLayout.setHorizontalGroup(
            leaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        leaderboardLayout.setVerticalGroup(
            leaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jPanel4.add(leaderboard, "card3");

        AboutmePanel.setBackground(new java.awt.Color(255, 255, 255));
        AboutmePanel.setPreferredSize(new java.awt.Dimension(753, 455));

        aboutmepng.setBackground(new java.awt.Color(255, 255, 255));
        aboutmepng.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutmetxt.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        aboutmetxt.setForeground(new java.awt.Color(255, 255, 255));
        aboutmetxt.setText("About Me");
        aboutmepng.add(aboutmetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 37));

        pict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/testgui/view/asss.png"))); // NOI18N
        aboutmepng.add(pict, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 120));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Name : Moch . Rama Andyasril");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nim    : 10116538");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Major : Informatics");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Class  : If - 12");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Faculty : Engineering and computer science");

        javax.swing.GroupLayout AMnameLayout = new javax.swing.GroupLayout(AMname);
        AMname.setLayout(AMnameLayout);
        AMnameLayout.setHorizontalGroup(
            AMnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AMnameLayout.setVerticalGroup(
            AMnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AMnameLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(0, 153, Short.MAX_VALUE))
        );

        aboutmepng.add(AMname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 300));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/testgui/view/asds.png"))); // NOI18N
        aboutmepng.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, 300));

        javax.swing.GroupLayout AboutmePanelLayout = new javax.swing.GroupLayout(AboutmePanel);
        AboutmePanel.setLayout(AboutmePanelLayout);
        AboutmePanelLayout.setHorizontalGroup(
            AboutmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutmepng, javax.swing.GroupLayout.PREFERRED_SIZE, 817, Short.MAX_VALUE)
        );
        AboutmePanelLayout.setVerticalGroup(
            AboutmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutmepng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.add(AboutmePanel, "card6");

        mainPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 760, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:


    }//GEN-LAST:event_formWindowOpened


    private void leaderbordbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaderbordbtnMouseClicked
       leaderboard.setVisible(true);
       Ripple.setVisible(false);
       FaqGames.setVisible(false);
    }//GEN-LAST:event_leaderbordbtnMouseClicked

    private void HomepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomepageMouseClicked
       Ripple.setVisible(true);
       FaqGames.setVisible(false);
       leaderboard.setVisible(false);


    }//GEN-LAST:event_HomepageMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void FaqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FaqMouseClicked
        FaqGames.setVisible(true);
        Ripple.setVisible(false);
        DonatePanel.setVisible(false);
        AboutmePanel.setVisible(false);
       
    
    
      

    }//GEN-LAST:event_FaqMouseClicked

    private void DonateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonateMouseClicked
        DonatePanel.setVisible(true);
        Ripple.setVisible(false);
        AboutmePanel.setVisible(false);
        leaderboard.setVisible(false);
    }//GEN-LAST:event_DonateMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Login n = new Login ();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void AboutMeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMeMouseClicked
         AboutmePanel.setVisible(true);
         FaqGames.setVisible(false);
         leaderboard.setVisible(false);
         Ripple.setVisible(false);
         
    }//GEN-LAST:event_AboutMeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AMname;
    private javax.swing.JLabel AboutMe;
    private javax.swing.JPanel AboutmePanel;
    private javax.swing.JLabel Donate;
    private javax.swing.JPanel DonatePanel;
    private javax.swing.JLabel Faq;
    private javax.swing.JPanel FaqGames;
    private javax.swing.JLabel Homepage;
    private javax.swing.JLabel HomepageBg;
    private javax.swing.JPanel Homepej;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Ripple;
    private javax.swing.JLabel RippleMiniLogo;
    private javax.swing.JPanel aboutmepng;
    private javax.swing.JLabel aboutmetxt;
    private javax.swing.JLabel howdy;
    private javax.swing.JPanel howdypanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel leaderboard;
    private javax.swing.JLabel leaderbordbtn;
    private javax.swing.JLabel logocaduk;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel pict;
    private javax.swing.JLabel wlcmb;
    // End of variables declaration//GEN-END:variables
}
